apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: prisoner-content-api
  description: The Prisoner Content Hub content API
  tags:
    - drupal
    - content
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: prisoner-content-hub
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml